version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - node_redis
    restart: unless-stopped

  redis:
    image: redis:latest
    networks:
      - node_redis
  
networks:
  node_redis:
    name: node_redis